contact_links:
    - name: Common Issues
      url: https://xplorer.space/docs/common_problems
      about: Please see if your issue is a common issue
    - name: Feature Request
      url: https://github.com/kimlimjustin/xplorer/discussions
      about: Suggest an idea or solution for this project
